In [46]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [47]:
fake_df = pd.read_csv("Fake.csv")
true_df = pd.read_csv("True.csv")

1. Find the total number of news articles.

In [48]:
print("Total News Articles:", len(fake_df))
print("Total News Articles:", len(true_df))

Total News Articles: 23481
Total News Articles: 21417

2.Find the count of Fake and Real news.

In [63]:
fake_df["label"] = "Fake"
true_df["label"] = "Real"

print(fake_df["label"].value_counts())
print(true_df["label"].value_counts())

label
Fake    23481
Name: count, dtype: int64
label
Real    21417
Name: count, dtype: int64

3. Find the percentage of Fake and Real news

In [64]:
df = pd.concat([fake_df, true_df], ignore_index=True)
print((df["label"].value_counts(normalize=True) * 100).round(2))

label
Fake    52.3
Real    47.7
Name: proportion, dtype: float64

4. Find the total number of subjects

In [51]:
print("Total Subjects:", df["subject"].nunique())

Total Subjects: 8

  5. Find all available subjects

In [52]:
print(df["subject"].unique())

['News' 'politics' 'Government News' 'left-news' 'US_News' 'Middle-east'
 'politicsNews' 'worldnews']

6. Find the count of news articles in each subject

In [53]:
df["subject"].value_counts()

subject
politicsNews       11272
worldnews          10145
News                9050
politics            6841
left-news           4459
Government News     1570
US_News              783
Middle-east          778
Name: count, dtype: int64

7. Find Fake and Real news count for each subject

In [54]:
pd.crosstab(df["subject"], df["label"])

label            Fake   Real
subject
Government News  1570      0
Middle-east       778      0
News             9050      0
US_News           783      0
left-news        4459      0
politics         6841      0
politicsNews        0  11272
worldnews           0  10145

8. Find the average article length

In [55]:
df["text_len"] = df["text"].apply(len)

print("Average Article Length:", df["text_len"].mean())

Average Article Length: 2469.1096930820972

9. Find the average word count

In [56]:
df["word_count"] = df["text"].apply(lambda x: len(x.split()))

print("Average Word Count:", df["word_count"].mean())

Average Word Count: 405.28228428883244

10. Find the longest news article

In [57]:
df.loc[df["word_count"].idxmax()]

title         MEDIA TRIPWIRE? Ping Pong Pizza Conspiracy Pro...
text           Funny how secrets travel. I d start to believ...
subject                                                 US_News
date                                          December 28, 2016
label                                                      Fake
text_len                                                  51794
word_count                                                 8135
Name: 22303, dtype: object

11. Find the shortest news article

In [58]:
df.loc[df["word_count"].idxmin(), ["title", "text", "word_count"]]

title         TAKE OUR POLL: Who Do You Think President Trum...
text
word_count                                                    0
Name: 10923, dtype: object

12. Find the top 10 longest news articles

In [59]:
df.nlargest(10, "word_count")[["title", "word_count"]]

                                                   title  word_count
22303  MEDIA TRIPWIRE? Ping Pong Pizza Conspiracy Pro...        8135
23086  MEDIA TRIPWIRE? Ping Pong Pizza Conspiracy Pro...        8135
21978  The Las Vegas Mass Shooting – More to the Stor...        7928
22761  The Las Vegas Mass Shooting – More to the Stor...        7928
22506  CULT CRIMES, MASS SHOOTINGS & MEDIA MIND CONTR...        7209
23289  CULT CRIMES, MASS SHOOTINGS & MEDIA MIND CONTR...        7209
9731   ANTI-AMERICAN GEORGE SOROS Locks Arms With NFL...        7033
17849  ANTI-AMERICAN GEORGE SOROS Locks Arms With NFL...        7033
12406  WOW! AMERICA IS UNDER ATTACK By These 187 Orga...        6608
19621  WOW! AMERICA IS UNDER ATTACK By These 187 Orga...        6608

13. Find the top 10 shortest news articles

In [60]:
df.nsmallest(10, "word_count")[["title", "word_count"]]

                                                   title  word_count
10923  TAKE OUR POLL: Who Do You Think President Trum...           0
11041  Joe Scarborough BERATES Mika Brzezinski Over “...           0
11190  WATCH TUCKER CARLSON Scorch Sanctuary City May...           0
11225  MAYOR OF SANCTUARY CITY: Trump Trying To Make ...           0
11236  SHOCKER: Public School Turns Computer Lab Into...           0
11241  BOOM! SEAN SPICER: “Trump Sold Hotels In Russi...           0
11247  MICHAEL FLYNN’S LAWYER Releases Statement Scor...           0
11249  ROB SCHNEIDER Nails The Russia Conspiracy Theo...           0
11267  TREY GOWDY ON SPYING ON AMERICAN CITIZENS…Like...           0
11268  SEAN SPICER CALLS OUT Race Baiting Journalist:...           0

14. Find the earliest and latest news date

In [61]:
print("Earliest Date:", df["date"].min())
print("Latest Date:", df["date"].max())

Earliest Date: 14-Feb-18
Latest Date: https://fedup.wpengine.com/wp-content/uploads/2015/04/hillarystreetart.jpg

15. Find the number of news articles published each month

In [69]:
print(df["date"].dtype)
df["date"] = df["date"].astype(str).str.strip()

df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce",
    format="mixed"
)

print(df["date"].dtype)
df.groupby(df["date"].dt.to_period("M")).size()

datetime64[ns]
datetime64[ns]

date
2015-03       8
2015-04     326
2015-05     338
2015-06     236
2015-07     291
2015-08     220
2015-09     202
2015-10     281
2015-11     276
2015-12     301
2016-01    1327
2016-02    1452
2016-03    1578
2016-04    1360
2016-05    1406
2016-06    1290
2016-07    1221
2016-08    1157
2016-09    1287
2016-10    1418
2016-11    1641
2016-12    1333
2017-01    1779
2017-02    1470
2017-03    1750
2017-04    1348
2017-05    1332
2017-06    1370
2017-07    1317
2017-08    1452
2017-09    3710
2017-10    3777
2017-11    3619
2017-12    2980
2018-02      35
Freq: M, dtype: int64

16. Find the month with the highest number of news articles

In [68]:
df.groupby(df["date"].dt.to_period("M")).size().sort_values(ascending=False).head()

date
2017-10    3777
2017-09    3710
2017-11    3619
2017-12    2980
2017-01    1779
Freq: M, dtype: int64